### ISSUE TITLE
WEBSITE IS SLOW!

### ISSUE THREAD

**Issue by FabianGabor** [FabianGabor/Selenium#1]
[http://selenium.fabiangabor.com/](http://selenium.fabiangabor.com/) is slow.

**Comment by kenovagyok** [comment]
tesztelni fogom jmeterrel

**Comment by FabianGabor** [comment]
OK én is

**Comment by FabianGabor** [comment]
Teszteltem 400 felhasználóval 10 másodpercen keresztül.

![Screenshot from 2020-11-24 10-19-37](https://user-images.githubusercontent.com/1741703/100074149-b1287200-2e3e-11eb-9f3a-8379e2b6bc63.png)
![Screenshot from 2020-11-24 10-19-54](https://user-images.githubusercontent.com/1741703/100074156-b38acc00-2e3e-11eb-9535-e5891a416218.png)
![Screenshot from 2020-11-24 10-19-58](https://user-images.githubusercontent.com/1741703/100074159-b4236280-2e3e-11eb-9d28-6ad99eee1d01.png)

**Comment by FabianGabor** [comment]
```
gabor@REACTOR-Ubuntu:~/Documents/jmeter/selenium$ jmeter -n -t selenium.jmx -l selenium.jtl
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/usr/share/java/xstream.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Security framework of XStream not initialized, XStream is probably vulnerable.
Creating summariser <summary>
Created the tree successfully using selenium.jmx
Starting the test @ Tue Nov 24 10:31:09 CET 2020 (1606210269219)
Waiting for possible shutdown message on port 4445
summary =    400 in    17s =   24.0/s Avg:  4120 Min:    48 Max:  8712 Err:   122 (30.50%)
Tidying up ...    @ Tue Nov 24 10:31:25 CET 2020 (1606210285900)
... end of run

```

[selenium.jmx.txt](https://github.com/FabianGabor/Selenium/files/5588784/selenium.jmx.txt)
[selenium.jtl.txt](https://github.com/FabianGabor/Selenium/files/5588786/selenium.jtl.txt)
[jmeter.log.txt](https://github.com/FabianGabor/Selenium/files/5588787/jmeter.log.txt)

**Comment by FabianGabor** [comment]
![htop 2020-11-24_11-02](https://user-images.githubusercontent.com/1741703/100079207-a96bcc00-2e44-11eb-8da8-1bb93d6d2f44.png)

15000 felhasználó 600 másodperc alatt (25 user/sec).

![jmeter-progress](https://user-images.githubusercontent.com/1741703/100079501-036c9180-2e45-11eb-8cd5-2c88f1657726.png)

**Comment by FabianGabor** [comment]
![Screenshot_2020-11-24 dirtyred - DigitalOcean](https://user-images.githubusercontent.com/1741703/100080518-382d1880-2e46-11eb-8afd-81c8eadfc5a0.png)

**Comment by FabianGabor** [comment]
Egy kis cache optimizálás után ráengedtem 6000 usert 60 másodpercig (100 user/sec), ami átlagos terhelésnek számít egy közepes méretű webshop esetén.

![Screenshot from 2020-11-24 14-48-26](https://user-images.githubusercontent.com/1741703/100103624-6d952e80-2e65-11eb-88bc-3a2c9aeb7a24.png)

![2020-11-24_15-00](https://user-images.githubusercontent.com/1741703/100103974-dd0b1e00-2e65-11eb-88c6-1289f5c3e67f.png)


Terhelés elhanyagolható. 3% körül az nginx, php inaktív a 60 sec cache miatt:

![Screenshot from 2020-11-24 14-48-27](https://user-images.githubusercontent.com/1741703/100103032-ae407800-2e64-11eb-99b7-f68052aa1242.png)

Tesztfile-ok és logok:

[selenium.jmx.txt](https://github.com/FabianGabor/Selenium/files/5590313/selenium.jmx.txt)
[selenium.jtl.txt](https://github.com/FabianGabor/Selenium/files/5590315/selenium.jtl.txt)
[jmeter.log.txt](https://github.com/FabianGabor/Selenium/files/5590321/jmeter.log.txt)

**Comment by FabianGabor** [comment]
[loader.io](https://bit.ly/3l19vwq)-n ráengedtem 9000 felhasználót 1 percen keresztül (150 user/sec).

A webszerver 5% alatt volt mindvégig.

![loaderio-01-9000user-1min](https://user-images.githubusercontent.com/1741703/100106292-ad114a00-2e68-11eb-9531-891a7fe89dda.png)

**Comment by Rzol3** [comment]
6000 felhasználó 60 másodperc alatt (100 user/s)

Beállítások
![rft4](https://user-images.githubusercontent.com/70938890/100111671-9a017880-2e6e-11eb-8eff-6dd4628272f4.png)

![rft3](https://user-images.githubusercontent.com/70938890/100111725-adacdf00-2e6e-11eb-8dfd-f75e34acc4ed.png)

Graph
![rft2](https://user-images.githubusercontent.com/70938890/100111750-b69db080-2e6e-11eb-8198-95a7d6e4ffb5.png)

Console
![rft1](https://user-images.githubusercontent.com/70938890/100111807-cf0dcb00-2e6e-11eb-8f9e-f1334e319a6a.png)

**Comment by kenovagyok** [comment]
![futtatas](https://user-images.githubusercontent.com/70938879/100541274-fedc1a80-3242-11eb-8f68-6c44684d9923.png)

**Comment by kenovagyok** [comment]
![Névtelen](https://user-images.githubusercontent.com/70938879/100541326-84f86100-3243-11eb-8097-346dcb273dee.png)
![Névtelen2](https://user-images.githubusercontent.com/70938879/100541327-86298e00-3243-11eb-85bb-7b623ea5efe0.png)
